version: '3.4'

services:
  device-registry:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:80


#   # dashboard:
#   #   image:
#   #   volumes:
#   #     - ./website:/var/www/html
#   #   ports:
#   #     - 5000:80
#   #   depends_on: 
#   #     - device-registry
  